workflows:
  android_debug:
    name: Build Debug APK - StopBetPro
    max_build_duration: 60
    environment:
      node: 18.18.0
      java: 17
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
    scripts:
      - name: Install Node dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Prepare Android
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew --version
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
