workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 60

    environment:
      java: 17
      node: 18
      npm: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
