workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.stopbetpro"
      java: 17
      node: 18
      npm: default
      android_signing:
        - stopbetpro_keystore

    scripts:
      - name: Instalar dependências
        script: |
          npm install

      - name: Limpar build antiga
        script: |
          cd android
          ./gradlew clean

      - name: Gerar APK Release
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
